module.exports = {
  DATA_MUST_BE_ARRAY: "10001 DATA_MUST_BE_ARRAY 傳入的資料必須為 array",
  DATA_MUST_BE_OBJECT: "10002 DATA_MUST_BE_OBJECT 傳入的資料必須為 object",
  FIELD_REQUIRED: "10003 FIELD_REQUIRED 缺少資料欄位",
  BAD_REQUEST: "10004 BAD_REQUEST 錯誤的請求格式",
  JOI_VALIDATION_ERROR: "10005 JOI_VALIDATION_ERROR 輸入參數格式錯誤",
  PARAMETER_ERROR: "10006 PARAMETER_ERROR 參數錯誤",
  BAD_FILE_REQUEST: "10007 BAD_FILE_REQUEST 錯誤的檔案格式",

  // 系統核心錯誤 相關錯誤
  ERROR_UNDEFINED: "99998 ERROR_UNDEFINED 未定義錯誤",
  BAD_ERROR: "99999 BAD_ERROR 不正確的錯誤呼叫",
};
